package org.finiteplay.holdem.opponents

// GENERATED by PreflopTableGenerator (test sources). Do not edit.
internal object PreflopData {
    val CLASS_LOW = IntArray(169) { it * 50 }
    val CLASS_HIGH = IntArray(169) { (it + 1) * 50 }
    val PUSH = Array(75) { "1".repeat(169) }
    val CALL_PUSH = Array(75) { "1".repeat(169) }
}
