package org.finiteplay.blackjack.rules

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.random.Random

/** `EXECUTION_PLAN.md` B6's gate. */
class BasicStrategyTest {
    private val generated by lazy { BasicStrategyGenerator.generate() }

    @Test
    fun `the committed table is exactly what the generator produces, cell for cell`() {
        assertEquals(generated.hard, BasicStrategy.HARD)
        assertEquals(generated.soft, BasicStrategy.SOFT)
        assertEquals(generated.pairs, BasicStrategy.PAIRS)
    }

    /**
     * Cells whose two best actions are within [BasicStrategyGenerator.CLOSE_MARGIN] of each other.
     * Listed rather than left to chance: a rule or generator change that moves one is a decision.
     */
    @Test
    fun `the close cells are the committed ones`() {
        assertEquals(
            listOf(
                "hard 9 vs 2", "hard 12 vs 4", "hard 16 vs 10", "soft 12 vs 6", "soft 13 vs 5",
                "soft 15 vs 4", "soft 17 vs 2", "soft 18 vs 2", "soft 18 vs A", "pair 3 vs 2",
            ),
            generated.closeCells,
        )
    }

    /**
     * The published six-deck, dealer-stands-on-soft-17, double-after-split, no-surrender chart, as
     * background rather than contract. The generated table agrees with it in every cell, so there
     * is no difference to explain; any future one must be explained here or fixed.
     */
    @Test
    fun `the table agrees with the published chart`() {
        val hard = mapOf(
            9 to "HDDDDHHHHH", 10 to "DDDDDDDDHH", 11 to "DDDDDDDDDH", 12 to "HHHSSHHHHH",
            13 to "SSSSSHHHHH", 14 to "SSSSSHHHHH", 15 to "SSSSSHHHHH", 16 to "SSSSSHHHHH", 17 to "SSSSSSSSSS",
        )
        for ((total, row) in hard) assertEquals("hard $total", row, BasicStrategy.HARD.getValue(total))
        val soft = mapOf(
            13 to "HHHDDHHHHH", 14 to "HHHDDHHHHH", 15 to "HHDDDHHHHH", 16 to "HHDDDHHHHH",
            17 to "HDDDDHHHHH", 18 to "SddddSSHHH", 19 to "SSSSSSSSSS",
        )
        for ((total, row) in soft) assertEquals("soft $total", row, BasicStrategy.SOFT.getValue(total))
        val pairs = mapOf(
            1 to "PPPPPPPPPP", 2 to "PPPPPPHHHH", 3 to "PPPPPPHHHH", 4 to "HHHPPHHHHH", 5 to "DDDDDDDDHH",
            6 to "PPPPPHHHHH", 7 to "PPPPPPHHHH", 8 to "PPPPPPPPPP", 9 to "PPPPPSPPSS", 10 to "SSSSSSSSSS",
        )
        for ((value, row) in pairs) assertEquals("pair $value", row, BasicStrategy.PAIRS.getValue(value))
    }

    @Test
    fun `double entries fall back to an offered action`() {
        // 5 + 6 against a six doubles; without the bankroll for it, it hits.
        val eleven = stateWith(listOf(PlayerHand(cards("5C", "6H"), 100)), dealer = cards("6S", "TH"))
        assertEquals(Decision.DOUBLE, BasicStrategy.recommend(eleven, 1_000))
        assertEquals(Decision.HIT, BasicStrategy.recommend(eleven, 150))
        // Three cards cannot double either.
        val three = stateWith(listOf(PlayerHand(cards("2C", "3H", "6D"), 100)), dealer = cards("6S", "TH"))
        assertEquals(Decision.HIT, BasicStrategy.recommend(three, 1_000))
        // Soft 18 against a six: double else stand.
        val soft = stateWith(listOf(PlayerHand(cards("AC", "7H"), 100)), dealer = cards("6S", "TH"))
        assertEquals(Decision.DOUBLE, BasicStrategy.recommend(soft, 1_000))
        assertEquals(Decision.STAND, BasicStrategy.recommend(soft, 150))
    }

    @Test
    fun `a pair that cannot split is played as its total`() {
        // 8,8 against a ten: split is the table's answer; without the bankroll, hard 16 hits.
        val eights = stateWith(listOf(PlayerHand(cards("8C", "8H"), 100)), dealer = cards("TS", "7H"))
        assertEquals(Decision.SPLIT, BasicStrategy.recommend(eights, 1_000))
        assertEquals(Decision.HIT, BasicStrategy.recommend(eights, 150))
        // Aces that cannot split are soft 12.
        val aces = stateWith(listOf(PlayerHand(cards("AC", "AH"), 100)), dealer = cards("TS", "7H"))
        assertEquals(Decision.HIT, BasicStrategy.recommend(aces, 150))
    }

    @Test
    fun `insurance is always declined`() {
        val state = stateWith(listOf(PlayerHand(cards("TC", "9H"), 100)), dealer = cards("AS", "5H"), phase = Phase.INSURANCE)
        assertEquals(Decision.DECLINE_INSURANCE, BasicStrategy.recommend(state, 1_000))
    }

    @Test
    fun `across random legal play the hint is always an offered action`() {
        val random = Random(77)
        var hints = 0
        repeat(3_000) {
            val bankroll = listOf(20, 100, 150, 300, 1_000).random(random)
            val bet = (Chips.MIN_BET..Chips.maxBetFor(bankroll) step Chips.BET_STEP).toList().random(random)
            var session = startRound(random.nextLong(), bet, bankroll)
            while (session.state.phase != Phase.SETTLED) {
                val legal = legalDecisions(session.state, bankroll)
                val hint = BasicStrategy.recommend(session.state, bankroll)
                assertNotNull(hint)
                assertTrue("hint $hint is not among $legal", hint in legal)
                hints++
                val choice = if (Decision.SPLIT in legal && random.nextInt(10) < 6) Decision.SPLIT else legal.random(random)
                session = session.decide(choice, bankroll)!!
            }
            assertNull(BasicStrategy.recommend(session.state, bankroll))
        }
        assertTrue(hints > 3_000)
    }
}
