package org.finiteplay.holdem.opponents

import org.finiteplay.cards.SplitMix64

/**
 * Writes `PreflopData.kt`: the 169 classes ranked by equity against a random hand, the push-or-fold
 * sets for 1 to 15 big blinds, and the call-off sets against a push. Deterministic (fixed seeds and
 * sample counts), so a test can hold the committed file to it. It lives in test sources so that none
 * of it reaches the app (`EXECUTION_PLAN.md` H7).
 *
 * Regenerate with `WRITE_PREFLOP_TABLES=1 ./gradlew.bat :games:holdem:opponents:test --tests '*PreflopTablesTest*'`.
 */
object PreflopTableGenerator {
    private const val RANK_SAMPLES = 40_000
    private const val CALL_SAMPLES = 4_000
    private const val CALL_MARGIN = 0.02

    private fun idOf(rank: Int, suit: Int) = suit * 13 + if (rank == 12) 0 else rank + 1

    private fun representative(c: Int): IntArray {
        val hi = HandClasses.high(c)
        val lo = HandClasses.low(c)
        return when {
            HandClasses.isPair(c) -> intArrayOf(idOf(hi, 0), idOf(hi, 1))
            HandClasses.isSuited(c) -> intArrayOf(idOf(hi, 0), idOf(lo, 0))
            else -> intArrayOf(idOf(hi, 0), idOf(lo, 1))
        }
    }

    private fun equityAgainst(c: Int, range: DoubleArray, samples: Int, seed: Long): Double {
        val h = representative(c)
        return Equity.estimate(h[0], h[1], IntArray(0), listOf(range), samples, SplitMix64(seed))
    }

    private fun closure(set: BooleanArray): BooleanArray {
        val out = set.copyOf()
        var changed = true
        while (changed) {
            changed = false
            for (a in 0 until HandClasses.COUNT) if (!out[a]) {
                for (b in 0 until HandClasses.COUNT) if (out[b] && HandClasses.dominates(a, b)) {
                    out[a] = true
                    changed = true
                    break
                }
            }
        }
        return out
    }

    private fun row(set: BooleanArray) = set.joinToString("") { if (it) "1" else "0" }

    fun generate(): String {
        val uniform = DoubleArray(Combos.COUNT) { 1.0 }
        val score = DoubleArray(HandClasses.COUNT) { equityAgainst(it, uniform, RANK_SAMPLES, 1000L + it) }
        // A class that beats another on every count must rank above it, whatever the sampling said.
        var changed = true
        while (changed) {
            changed = false
            for (a in 0 until HandClasses.COUNT) for (b in 0 until HandClasses.COUNT) {
                if (HandClasses.dominates(a, b) && score[a] <= score[b]) {
                    score[a] = score[b] + 1e-6
                    changed = true
                }
            }
        }
        val order = (0 until HandClasses.COUNT).sortedWith(compareByDescending<Int> { score[it] }.thenBy { it })
        val low = IntArray(HandClasses.COUNT)
        val high = IntArray(HandClasses.COUNT)
        var cum = 0
        for (c in order) {
            low[c] = cum * 10_000 / Combos.COUNT
            cum += HandClasses.combos(c)
            high[c] = cum * 10_000 / Combos.COUNT
        }

        fun pushSet(stack: Int, behind: Int): BooleanArray {
            val width = PreflopRanges.pushWidth(stack, behind)
            return closure(BooleanArray(HandClasses.COUNT) { (low[it] + high[it]) / 2 <= width })
        }

        val push = ArrayList<String>()
        val callPush = ArrayList<String>()
        for (stack in 1..PreflopRanges.MAX_PUSH_STACK) {
            for (behind in 1..5) push += row(pushSet(stack, behind))
            val pusher = pushSet(stack, PreflopRanges.ASSUMED_PUSHER_BEHIND)
            val range = DoubleArray(Combos.COUNT) { if (pusher[Combos.classOf[it]]) 1.0 else 0.0 }
            val eq = DoubleArray(HandClasses.COUNT) { equityAgainst(it, range, CALL_SAMPLES, 5000L + 200L * stack + it) }
            for (need in PreflopRanges.needed) callPush += row(closure(BooleanArray(HandClasses.COUNT) { eq[it] >= need + CALL_MARGIN }))
        }
        return buildString {
            appendLine("package org.finiteplay.holdem.opponents")
            appendLine()
            appendLine("// GENERATED by PreflopTableGenerator (test sources). Do not edit.")
            appendLine("internal object PreflopData {")
            appendLine("    val CLASS_LOW = intArrayOf(${low.joinToString(", ")})")
            appendLine("    val CLASS_HIGH = intArrayOf(${high.joinToString(", ")})")
            appendLine("    val PUSH = arrayOf(")
            for (r in push) appendLine("        \"$r\",")
            appendLine("    )")
            appendLine("    val CALL_PUSH = arrayOf(")
            for (r in callPush) appendLine("        \"$r\",")
            appendLine("    )")
            appendLine("}")
        }
    }
}
