package org.finiteplay.klondike.tools.catalog

import java.io.File

/**
 * Turns a calibration CSV into the seed lists `:app` ships for one robustness-graded tier.
 *
 * Seeds are emitted **most robust first** — every deal surviving the largest number of
 * mistakes, then the next, and so on down to the tier's floor. A player works through the
 * tier in order, so the most forgiving hands come first and the band tightens as they go: by
 * the time anyone reaches the far end they have played through thousands of hands and are no
 * longer the beginner the first ones were written for.
 *
 * Output is **chunked across files**, not one list. Each Kotlin file compiles its top-level
 * properties into that file's own static initializer, and the existing tier files already
 * warn that six thousand entries in one initializer risks the JVM's 64 KB method limit. Five
 * thousand sits close enough to that ceiling to be worth splitting; separate files each get
 * their own initializer, whereas separate properties in one file would not.
 */
fun exportTrivialCatalog(
    csvPath: String,
    outputDir: String,
    minBudget: Int = 3,
    perChunk: Int = 1500,
    tier: String = "Trivial",
    /** Upper bound on the graded value, for a tier scored on a band rather than a floor. */
    maxBudget: Int = Int.MAX_VALUE,
    /**
     * Whether a **lower** graded value is the more forgiving one. False for the robustness
     * tiers, where the value is a mistake budget and more is better; true for Expert, where it
     * counts critical choices and fewer is better. Either way the tier opens on its kindest
     * hands, which is the only thing the ordering is for.
     */
    ascending: Boolean = false,
    bandLabel: String = "survives",
    log: (String) -> Unit = ::println,
) {
    val rows = File(csvPath).readLines()
        .drop(1)
        .mapNotNull { line ->
            val parts = line.split(',')
            val seed = parts.getOrNull(0)?.trim()?.toLongOrNull() ?: return@mapNotNull null
            val budget = parts.getOrNull(1)?.trim()?.toIntOrNull() ?: return@mapNotNull null
            seed to budget
        }
        .filter { it.second in minBudget..maxBudget }

    if (rows.isEmpty()) {
        log("no seeds at budget >= $minBudget in $csvPath — nothing written")
        return
    }

    // Most forgiving first, and by seed within a band so the output is reproducible.
    val ordered = if (ascending) {
        rows.sortedWith(compareBy<Pair<Long, Int>> { it.second }.thenBy { it.first })
    } else {
        rows.sortedWith(compareByDescending<Pair<Long, Int>> { it.second }.thenBy { it.first })
    }
    val byBudget = ordered.groupBy { it.second }.toSortedMap(if (ascending) naturalOrder() else compareByDescending { it })

    log("read ${rows.size} seeds in $minBudget..$maxBudget")
    for ((budget, seeds) in byBudget) log("  $bandLabel $budget: ${seeds.size}")

    val upper = tier.uppercase()
    val chunks = ordered.map { it.first }.chunked(perChunk)
    val directory = File(outputDir).apply { mkdirs() }

    // Delete every existing part first. A smaller tier writes fewer files than the last run,
    // and the leftovers are not harmless: they still compile, so a stale part can be read as
    // live catalog content by anything scanning the directory.
    directory.listFiles { f -> f.name.matches(Regex("""InterimSeeds$tier[A-Z]\.kt""")) }
        ?.forEach { part -> if (part.delete()) log("cleared stale part ${part.name}") }
    val chunkNames = chunks.indices.map { "INTERIM_SEEDS_${upper}_${'A' + it}" }

    chunks.forEachIndexed { index, seeds ->
        val name = chunkNames[index]
        val file = File(directory, "InterimSeeds$tier${'A' + index}.kt")
        file.printWriter().use { out ->
            out.println("package org.finiteplay.klondike.deal")
            out.println()
            out.println("/**")
            out.println(" * $tier seeds, part ${index + 1} of ${chunks.size}, most robust first")
            out.println(" * (`docs/games/klondike/DIFFICULTY_LEVELS.md`, \"$tier\"). Generated by")
            out.println(" * `tools/catalog`'s `build-${tier.lowercase()}-tier`; do not edit by hand.")
            out.println(" *")
            out.println(" * Split across files because each file compiles its own static initializer, and one")
            out.println(" * list of every $tier seed would risk the JVM's 64 KB method limit.")
            out.println(" */")
            out.println("internal val $name: List<Long> = listOf(")
            for (seed in seeds) out.println("    ${seed}L,")
            out.println(")")
        }
        log("wrote ${file.name}: ${seeds.size} seeds")
    }

    val index = File(directory, "InterimSeeds$tier.kt")
    index.printWriter().use { out ->
        out.println("package org.finiteplay.klondike.deal")
        out.println()
        out.println("/**")
        out.println(" * Draw-one seeds graded **$tier**: a player using only obvious moves, in this tier's")
        out.println(" * priority order, wins them even while making mistakes")
        out.println(" * (`docs/games/klondike/DIFFICULTY_LEVELS.md`, \"$tier\").")
        out.println(" *")
        out.println(" * Ordered most robust first, so the tier opens at its most forgiving and tightens as a")
        out.println(" * player works through it. The parts exist only to keep each static initializer under")
        out.println(" * the JVM's 64 KB method limit; concatenating them is the whole list.")
        out.println(" *")
        out.println(" * Regenerate with `tools/catalog`'s `calibrate-${tier.lowercase()}` then `build-${tier.lowercase()}-tier`.")
        out.println(" */")
        out.println("internal val INTERIM_SEEDS_$upper: List<Long> = ${chunkNames.joinToString(" + ")}")
    }
    log("wrote ${index.name}: concatenates ${chunks.size} parts, ${ordered.size} seeds total")
}
